### ISSUE TITLE
Absolute imports?

### ISSUE THREAD

**Issue by omgo** [clinyong/vscode-css-modules#19]
Is it possible to use "go to definition" with absolute import?

import styles from 'styles/myAwesomeStyles.css';
(projectFolder/src/styles)

**Comment by matepaiva** [comment]
Hello :) Did you find any workaround to make it work with absolute imports?

**Comment by iChenLei** [comment]
closed https://github.com/clinyong/vscode-css-modules/pull/40 , you can set alias paths in tsconfig.json (or jsconfig.json) in your project. Thanks for feedback.
