### ISSUE TITLE
Open VSX support

### ISSUE THREAD

**Issue by FerrielMelarpis** [clinyong/vscode-css-modules#33]
Hi there.
First of all, thank you for this plugin.
I just started using [Onivim 2](https://onivim.github.io/) and found out that I can install extensions from https://open-vsx.org/.
I've used this plugin in my VS Code and thought that it would be nice to have it available in Open VSX marketplace as well.

I would like to request this plugin to be published there as well if you don't mind. I found some instructions here https://onivim.github.io/docs/configuration/extensions#publishing-an-extension. Let me know how I can help.

**Comment by clinyong** [comment]
Sounds like interesting. I will check the publish instruction later.

**Comment by clinyong** [comment]
I have published the extension to open vsx, <https://open-vsx.org/extension/clinyong/vscode-css-modules>. I don't use Onivim, so I haven't test the plugin with this editor. If you meet some problem, let me know.

BTW, I am claiming the namespace to remove the homepage warning. <https://github.com/EclipseFdn/open-vsx.org/issues/582>.

**Comment by FerrielMelarpis** [comment]
Thank you 🙏🏼
