### ISSUE TITLE
compose

### ISSUE THREAD

**Issue by polizz** [clinyong/vscode-css-modules#4]
I saw that you responded to a (vscode issue thread)[https://github.com/Microsoft/vscode/issues/13003] saying that this module fixed linting errors on the compose keyword. I still have an issue with linting in a SCSS syntax CSS module. I can't even get vscode to ignore the single line so that's not an option and I really do not want to disable all validation.

I reformatted this SCSS file to be CSS and still got the issue, albeit a warning instead of an error.  Have you seen this?

<img width="151" alt="screen shot 2017-03-02 at 1 58 37 pm" src="https://cloud.githubusercontent.com/assets/10888433/23524497/82ff3542-ff50-11e6-9911-cf609d0dcaa9.png">

**Comment by clinyong** [comment]
May be a mistake...

This plugin only support `autocomplete` and `go to definition`, no lint feature.

I recommend to use sass syntax with css modules scope feature.
