### ISSUE TITLE
require bug

### ISSUE THREAD

**Issue by www159** [clinyong/vscode-css-modules#52]
as I use it as suggestion, some trouble things descend.
like below:
![image](https://user-images.githubusercontent.com/40891547/137576533-455a372f-e357-47b5-ad05-a12a22780f4b.png)

but when serving:
![image](https://user-images.githubusercontent.com/40891547/137576553-5b31c42d-4725-4956-8108-c1dc12bd2b99.png)

however, as I try to use `styles.defaut.<cssName>`, it does work
![image](https://user-images.githubusercontent.com/40891547/137576587-e3e8bc2d-516a-4fbe-b9a2-9d72a2785693.png)
**and I lose the intellisense in this way**
what' wrong ::sad

**Comment by iChenLei** [comment]
It looks like extension didn't treat CommonJS differently from ESModule
cc @clinyong

**Comment by clinyong** [comment]
@www159 Please use import here

```
import * as styles from './index.module.less'
```

Feel free to reopen the issue if you have any other problem.
