### ISSUE TITLE
add support for .js

### ISSUE THREAD

**Issue by budiantotan** [clinyong/vscode-css-modules#7]
Hi, could you add support for .js files as well? we could write jsx codes in .js file within vs-code, it'll be nice if we could have css-modules supported for .js file as well.

**Comment by clinyong** [comment]
If you write jsx in `.js` file, add below to your vscode setting

```json
"files.associations": {
    "*.js": "javascriptreact"
},
```

It will also enable the plugin in `.js` file.

**Comment by budiantotan** [comment]
yeah, that works. but CMIIW, that means .js don't associated as javascript anymore. in my case, not all of .js files are jsx, could be just some pure js code.  it might cause other extensions doesn't activated on .js files anymore (if it only supports javascript).

**Comment by clinyong** [comment]
> that means `.js` don't associated as javascript anymore

No. `jsx` is still javascript.

> in my case, not all of .js files are jsx, could be just some pure js code. 

In my project, I have this situation too.

In most case, I think it will not cause any problem.  It is easy to support `javascript`, but I think it is no necessary. But if you really get the problem, let me know. (Maybe you can tell me which extension doesn't active.)

BTW, I am suggest that if you are using jsx, your file extension should be `jsx`, not `js`. Otherwise, your vscode doesn't work well, like formatting code in a `.js` file with jsx code.

**Comment by budiantotan** [comment]
> In most case, I think it will not cause any problem. It is easy to support javascript, but I think it is no necessary. But if you really get the problem, let me know. (Maybe you can tell me which extension doesn't active.)
currently all works just fine, will let you know if i encountered the problem 😄 

>BTW, I am suggest that if you are using jsx, your file extension should be jsx, not js. Otherwise, your vscode doesn't work well, like formatting code in a .js file with jsx code.
yeah, i am renaming those files now. thanks for the response!

**Comment by mo** [comment]
FWIW; If I rename my .js to .jsx then the extension "Switcher" (blackmery.vscode-switcher) doesn't work anymore. I use it to quickly toggle between the .js and .css files. Setting files.associations worked though.

**Comment by ro-savage** [comment]
@clinyong I'd like to see .js files associated with this plugin by default. 

There are people who use CSS Modules outside of React, plus it means those who use `.js` dont have to search your github issues to figure out how to get the plugin working.

I only just started trying out VSCode but all the behaviour seems to work for React even though everything is `.js`. I am not sure what default behaviour works with `.jsx` but not `.js`.
