### ISSUE TITLE
Not working on next.js project

### ISSUE THREAD

**Issue by ivanschuetz** [clinyong/vscode-css-modules#78]
I installed this extension and it's not doing anything, navigation and autocomplete don't work.

I found a couple issues here where it appears that it should work on next.js (not react-only).

VSCode 1.73.1
Next 12.3.0

**Comment by clinyong** [comment]
Could you supply a reproduced demo?

**Comment by ivanschuetz** [comment]
@clinyong actually, I just noticed that the problem is specific to ids (when using the id attribute instead of class). Is that a known limitation?

Also, when using classes, is there a way to prevent this selection?

<img width="354" alt="Screen Shot 2022-11-24 at 16 30 44" src="https://user-images.githubusercontent.com/1381744/203820773-e347aec5-e017-45fe-8910-e81ac620c909.png">

These issues can be reproduced with a nextjs starter project:
```
npx create-next-app@latest nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
```

**Comment by clinyong** [comment]
Yes, the id attribute is not supported. We can't prevent the selection because there isn't an api for extension to do this.

**Comment by ivanschuetz** [comment]
Would a feature request for the id make sense? And about the api, would it make sense to open an issue on the vscode repo maybe (I could do it)?

**Comment by karlhorky** [comment]
I think the "duplicate definitions in Go to Definition" issue is documented over here:

- https://github.com/clinyong/vscode-css-modules/issues/63

As I mentioned in my last comments, someone could open an issue in the `microsoft/vscode` or `microsoft/TypeScript` repos to present the use case clearly and ask for some way for an extension (or user configuration) to be able to disable useless definition entries in Go to Definition.

**Comment by iChenLei** [comment]
> @clinyong actually, I just noticed that the problem is specific to ids (when using the id attribute instead of class). Is that a known limitation?
> 
> Also, when using classes, is there a way to prevent this selection?
> 
> <img alt="Screen Shot 2022-11-24 at 16 30 44" width="354" src="https://user-images.githubusercontent.com/1381744/203820773-e347aec5-e017-45fe-8910-e81ac620c909.png">
> 
> These issues can be reproduced with a nextjs starter project:
> 
> ```
> npx create-next-app@latest nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
> ```

Duplicate https://github.com/clinyong/vscode-css-modules/issues/63
