### ISSUE TITLE
Go to definition no longer works

### ISSUE THREAD

**Issue by stijnvanderlaan** [clinyong/vscode-css-modules#8]
When I try to Go to definition I get the message: 'No definition found for className'
My version of visual studio code is 1.11.2, previously it did work for me.

**Comment by clinyong** [comment]
@stijnvanderlaan Could you show me your js and css file? And what is your vscode-css-modules version?

**Comment by stijnvanderlaan** [comment]
Oh sorry I found the problem, I had installed a babel plugin which broke it. I just uninstalled it because it is not needed.
