### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by alexey-koran** [clinyong/vscode-css-modules#81]
Why did you remove support for `.ts` files?

**Comment by TheSwilliam** [comment]
We no longer have intellisense using styles in .ts files. Can you please add the support back in.

**Comment by iChenLei** [comment]
Why you using css modules in .ts files ? Any showcase for maintainers to understand your usage? Thanks

**Comment by TheSwilliam** [comment]
the example is that we have an interface that defines style themes for a library. I then have to create a myTheme.ts file to map my classes to the theme names.

mytheme.module.css
```
.myBackground{
    background: red;
}
```
typescript theme interface
```
interface ITheme{
    backgroundTheme:string;
}
```
usage in MyTheme.ts
```
import styles from './mytheme.module.css'
const  myTheme: ITheme = {
    backgroundTheme: styles.myBackground;
}
```
