### ISSUE TITLE
"Go to definition" goes to d.ts file first, then to source

### ISSUE THREAD

**Issue by wildeyes** [clinyong/vscode-css-modules#9]
![image](https://cloud.githubusercontent.com/assets/1652108/25575669/15abc6fe-2e62-11e7-9810-0dcee799e50b.png)

It shouldn't bring up the .d.ts in the first place IMO, or at least focus on the source file instead of the .d.ts first.

Can you point me to how might I fix this?

**Comment by clinyong** [comment]
Why is there a `.d.ts` file?

**Comment by wildeyes** [comment]
It's generated by the tool "[typed-css-modules](https://github.com/Quramy/typed-css-modules)" and it's there to ensure all styles used do exist, instead of simply doing a catch-all "if css file than { [key: string]: string }".

**Comment by clinyong** [comment]
When using `typed-css-modules`, vscode detect there are multiple definitions. This is not controlled by the plugin.

I recommend to remove the `typed-css-modules` and related `.d.ts` files.

**Comment by cameron-martin** [comment]
But then you don't get type checking for your css files :(

**Comment by clinyong** [comment]
@cameron-martin what type checking meaning here?

**Comment by cameron-martin** [comment]
Typed-css-modules generates d.ts files for your CSS modules so typescript checks that you don't use CSS module identifiers that do not exist.

**Comment by cameron-martin** [comment]
A reasonable solution to this would be to only enable typed-css-modules in production builds so that type errors at least get caught by CI.

**Comment by FerrielMelarpis** [comment]
Does anyone know a workaround on this issue?

**Comment by wildeyes** [comment]
there's no workaround.
